swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /scan/:
    get:
      tags:
      - scan
      description: get layer
      operationId: ScanController.Get
      responses:
        "200": {}
    post:
      tags:
      - scan
      description: post
      operationId: ScanController.post
      responses:
        "200": {}
        "403": {}
  /scan/{namespace}/{repository}/{tag}:
    get:
      tags:
      - scan
      description: get layer
      operationId: ScanController.Get
      responses:
        "200": {}
  /scan/manifest:
    get:
      tags:
      - scan
      description: get layer
      operationId: ScanController.Get
      responses:
        "200": {}
  /scan/tags/{namespace}/{repository}/{tag}:
    get:
      tags:
      - scan
      description: get layer
      operationId: ScanController.Get
      responses:
        "200": {}
